version: '5'

services:
  prolog-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./src:/usr/share/nginx/html
    restart: always
    image: v4dikos/prolog-client:latest
